---
ID: "0ea4f2e9-e301-49a8-b183-a004df163fb2"
Parent: "b2ae7b7f-cd0f-4f2f-9d1c-b9e2e2bbab23"
Template: "b2ae7b7f-cd0f-4f2f-9d1c-b9e2e2bbab23"
Path: /sitecore/templates/Project/bupa/LinkBoxCard/LinkBoxCard Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260220T134647Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5f97b2f3-f90a-4ec2-931f-66df03638a70"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260504T105559Z
