---
ID: "bffaa001-0001-4ff1-aff1-a00100000020"
Parent: "bffaa001-0001-4ff1-aff1-a00100000010"
Template: "bffaa001-0001-4ff1-aff1-a00100000010"
Path: /sitecore/templates/Project/bupa/Footer/Footer/__Standard Values
SharedFields:
- ID: "bffaa001-0001-4ff1-aff1-a00100000016"
  Hint: MemberHelpLink
  Value: |
    <link text="Member help and support" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{C62DE7CE-DFE4-464C-8958-C9B7C6735399}" />
- ID: "bffaa001-0001-4ff1-aff1-a00100000017"
  Hint: SocialFacebookLink
  Value: |
    <link text="" anchor="" linktype="external" class="" title="" target="_blank" url="https://www.facebook.com" />
- ID: "bffaa001-0001-4ff1-aff1-a00100000018"
  Hint: SocialInstagramLink
  Value: |
    <link text="" anchor="" linktype="external" class="" title="" target="_blank" url="https://www.instagram.com" />
- ID: "bffaa001-0001-4ff1-aff1-a00100000019"
  Hint: SocialTiktokLink
  Value: |
    <link text="" anchor="" linktype="external" class="" title="" target="_blank" url="https://www.tiktok.com" />
- ID: "bffaa001-0001-4ff1-aff1-a0010000001a"
  Hint: SocialLinkedinLink
  Value: |
    <link text="" anchor="" linktype="external" class="" title="" target="_blank" url="https://www.linkedin.com" />
- ID: "bffaa001-0001-4ff1-aff1-a0010000001b"
  Hint: SocialYoutubeLink
  Value: |
    <link text="" anchor="" linktype="external" class="" title="" target="_blank" url="https://www.youtube.com" />
- ID: "bffaa001-0001-4ff1-aff1-a0010000001c"
  Hint: SocialXLink
  Value: |
    <link text="" anchor="" linktype="external" class="" title="" target="_blank" url="https://x.com" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260505T153000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bffaa001-ftr-sv-r"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "bffaa001-0001-4ff1-aff1-a00100000015"
      Hint: CopyrightLine
      Value: © Bupa 2026
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260505T153000Z
